---

# Deploy Web App
- import_playbook: ./libs/undeploy-web-app.yml
# Deploy Load Balancer
- import_playbook: ./libs/undeploy-load-balancer.yml
# Deploy App Server
- import_playbook: ./libs/undeploy-app-server.yml
# Deploy Database
- import_playbook: ./libs/undeploy-postgresql-database-server.yml
  # RPM Packages Repositories
- import_playbook: ./libs/yum-repo-teardown.yml

- name: Reverse sudoers
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Reverse the enabling of sudo without tty for some ansible commands
      replace:
        path: /etc/sudoers
        regexp: 'Defaults\s*!requiretty'
        replace: "^Defaults requiretty"
        backup: yes